In [ ]:
# Importung package pandas dan membaca dataset files
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/Movie_classification.csv')

In [ ]:
df.head()

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,3D_available,Time_taken,Twitter_hastags,Genre,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
0,201.264,59.62,462.0,36.524.125,138.7,7.825,8.095,7.910,7.995,7.94,527367,YES,109.60,223.840,Thriller,23,494,48000,1
1,205.462,69.14,531.0,35.668.655,152.4,7.505,7.650,7.440,7.470,7.44,494055,NO,146.64,243.456,Drama,42,462,43200,0
2,205.458,69.14,531.0,39.912.675,134.6,7.485,7.570,7.495,7.515,7.44,547051,NO,147.88,2022.400,Comedy,38,458,69400,1
3,206.474,59.36,542.0,38873.89,119.3,6.895,7.035,6.920,7.020,8.26,516279,YES,185.36,225.344,Drama,45,472,66800,1
4,21.381,59.36,542.0,39.701.585,127.7,6.920,7.070,6.815,7.070,8.26,531448,NO,176.48,225.792,Drama,55,395,72400,1

In [ ]:
df.tail()

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,3D_available,Time_taken,Twitter_hastags,Genre,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
501,212.526,78.86,427.0,36.624.115,142.6,8.68,8.775,8.620,8.970,6.8,492480,NO,186.96,243.584,Action,27,561,44800,0
502,209.054,78.86,427.0,33996.6,150.2,8.78,8.945,8.770,8.930,7.8,482875,YES,132.24,263.296,Action,20,600,41200,0
503,212.152,78.86,427.0,38751.68,164.5,8.83,8.970,8.855,9.010,7.8,532239,NO,109.56,243.824,Comedy,31,576,47800,0
504,221.918,78.86,427.0,37740.67,162.8,8.73,8.845,8.800,8.845,6.8,496077,YES,158.80,303.520,Comedy,47,607,44000,0
505,209.482,78.86,427.0,33496.65,154.3,8.64,8.880,8.680,8.790,6.8,518438,YES,205.60,203.040,Comedy,45,604,38000,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Marketing expense    506 non-null    object
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    object
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64
 11  3D_available         506 non-null    object
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object
 15  Avg_age_actors       506 non-null    int64
 16  Num_multiplex        506 non-null    int64
 17  Collection           506 non-null    int64
 18  Start_Tech_Oscar     506 non-null    int64
dtypes: float64(10), int64(5), object(4)
memory usage: 75.2+ KB

In [ ]:
df.describe()

,Production expense,Multiplex coverage,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,Time_taken,Twitter_hastags,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,494.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,77.273557,382.999097,142.074901,8.014002,8.185613,8.019664,8.190514,7.810870,449860.715415,157.391498,260.832095,39.181818,545.043478,45057.707510,0.545455
std,13.720706,192.003636,28.148861,1.054266,1.054290,1.059899,1.049601,0.659699,68917.763145,31.295161,104.779133,12.513697,106.332889,18364.351764,0.498422
min,55.920000,0.230000,76.400000,3.840000,4.035000,3.840000,4.030000,6.600000,212912.000000,0.000000,201.152000,3.000000,333.000000,10000.000000,0.000000
25%,65.380000,307.000000,118.525000,7.316250,7.503750,7.296250,7.507500,7.200000,409128.000000,132.300000,223.796000,28.000000,465.000000,34050.000000,0.000000
50%,74.380000,453.000000,151.000000,8.307500,8.495000,8.312500,8.465000,7.960000,462460.000000,160.000000,254.400000,39.000000,535.500000,42400.000000,1.000000
75%,91.200000,536.000000,167.575000,8.865000,9.030000,8.883750,9.030000,8.260000,500247.500000,181.890000,283.416000,50.000000,614.750000,50000.000000,1.000000
max,110.480000,615.000000,173.500000,9.435000,9.540000,9.425000,9.635000,9.400000,567784.000000,217.520000,2022.400000,60.000000,868.000000,100000.000000,1.000000

In [ ]:
df.describe().T
# matrik transpose. baris jd kolom dan sebaliknya

,count,mean,std,min,25%,50%,75%,max
Production expense,506.0,77.273557,13.720706,55.920,65.38000,74.3800,91.20000,110.480
Multiplex coverage,506.0,382.999097,192.003636,0.230,307.00000,453.0000,536.00000,615.000
Movie_length,506.0,142.074901,28.148861,76.400,118.52500,151.0000,167.57500,173.500
Lead_ Actor_Rating,506.0,8.014002,1.054266,3.840,7.31625,8.3075,8.86500,9.435
Lead_Actress_rating,506.0,8.185613,1.054290,4.035,7.50375,8.4950,9.03000,9.540
Director_rating,506.0,8.019664,1.059899,3.840,7.29625,8.3125,8.88375,9.425
Producer_rating,506.0,8.190514,1.049601,4.030,7.50750,8.4650,9.03000,9.635
Critic_rating,506.0,7.810870,0.659699,6.600,7.20000,7.9600,8.26000,9.400
Trailer_views,506.0,449860.715415,68917.763145,212912.000,409128.00000,462460.0000,500247.50000,567784.000
Time_taken,494.0,157.391498,31.295161,0.000,132.30000,160.0000,181.89000,217.520
Twitter_hastags,506.0,260.832095,104.779133,201.152,223.79600,254.4000,283.41600,2022.400
Avg_age_actors,506.0,39.181818,12.513697,3.000,28.00000,39.0000,50.00000,60.000
Num_multiplex,506.0,545.043478,106.332889,333.000,465.00000,535.5000,614.75000,868.000
Collection,506.0,45057.707510,18364.351764,10000.000,34050.00000,42400.0000,50000.00000,100000.000
Start_Tech_Oscar,506.0,0.545455,0.498422,0.000,0.00000,1.0000,1.00000,1.000

In [ ]:
df.isna()

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,3D_available,Time_taken,Twitter_hastags,Genre,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
502,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
503,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
504,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
505,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isna().sum()

Marketing expense       0
Production expense      0
Multiplex coverage      0
Budget                  0
Movie_length            0
Lead_ Actor_Rating      0
Lead_Actress_rating     0
Director_rating         0
Producer_rating         0
Critic_rating           0
Trailer_views           0
3D_available            0
Time_taken             12
Twitter_hastags         0
Genre                   0
Avg_age_actors          0
Num_multiplex           0
Collection              0
Start_Tech_Oscar        0
dtype: int64

In [ ]:
#jumlah missing value
df.isnull().sum()

Marketing expense       0
Production expense      0
Multiplex coverage      0
Budget                  0
Movie_length            0
Lead_ Actor_Rating      0
Lead_Actress_rating     0
Director_rating         0
Producer_rating         0
Critic_rating           0
Trailer_views           0
3D_available            0
Time_taken             12
Twitter_hastags         0
Genre                   0
Avg_age_actors          0
Num_multiplex           0
Collection              0
Start_Tech_Oscar        0
dtype: int64

In [ ]:
#melihat ukuran data (baris, kolom)
df.shape

(506, 19)

In [ ]:
# melihat
df.dtypes

Marketing expense       object
Production expense     float64
Multiplex coverage     float64
Budget                  object
Movie_length           float64
Lead_ Actor_Rating     float64
Lead_Actress_rating    float64
Director_rating        float64
Producer_rating        float64
Critic_rating          float64
Trailer_views            int64
3D_available            object
Time_taken             float64
Twitter_hastags        float64
Genre                   object
Avg_age_actors           int64
Num_multiplex            int64
Collection               int64
Start_Tech_Oscar         int64
dtype: object

In [ ]:
df.duplicated().sum() #melihat jumlah duplikasi data

0

In [ ]:
# melihat nilai kosong pada setiap kolom dalam persen
df.isna().sum()/len(df)*100
# jumlah data kosong dibagi panjang datanya dikali 100

Marketing expense      0.000000
Production expense     0.000000
Multiplex coverage     0.000000
Budget                 0.000000
Movie_length           0.000000
Lead_ Actor_Rating     0.000000
Lead_Actress_rating    0.000000
Director_rating        0.000000
Producer_rating        0.000000
Critic_rating          0.000000
Trailer_views          0.000000
3D_available           0.000000
Time_taken             2.371542
Twitter_hastags        0.000000
Genre                  0.000000
Avg_age_actors         0.000000
Num_multiplex          0.000000
Collection             0.000000
Start_Tech_Oscar       0.000000
dtype: float64

In [ ]:
# menghapus data yang memiliki missing value
df.dropna(inplace=True) #kalau inplace True terhapus permanen jika data dipanggil lagi. kalau False, data tidak terhapus permanen

In [ ]:
df.isna().sum()

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
3D_available           0
Time_taken             0
Twitter_hastags        0
Genre                  0
Avg_age_actors         0
Num_multiplex          0
Collection             0
Start_Tech_Oscar       0
dtype: int64

In [ ]:
# defaultnya False
df = df.dropna()

In [ ]:
df.isna().sum()

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
3D_available           0
Time_taken             0
Twitter_hastags        0
Genre                  0
Avg_age_actors         0
Num_multiplex          0
Collection             0
Start_Tech_Oscar       0
dtype: int64

In [ ]:
df.to_excel('Movie_classification.xlsx', index = False) #export datanya ke excel

In [ ]:
# simpan variabel klo inplacenya False

In [ ]:
bebas = pd.read_excel('Movie_classification.xlsx')
bebas.head()

,Unnamed: 0,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,3D_available,Time_taken,Twitter_hastags,Genre,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
0,0,201.264,59.62,462.0,36.524.125,138.7,7.825,8.095,7.910,7.995,7.94,527367,YES,109.60,223.840,Thriller,23,494,48000,1
1,1,205.462,69.14,531.0,35.668.655,152.4,7.505,7.650,7.440,7.470,7.44,494055,NO,146.64,243.456,Drama,42,462,43200,0
2,2,205.458,69.14,531.0,39.912.675,134.6,7.485,7.570,7.495,7.515,7.44,547051,NO,147.88,2022.400,Comedy,38,458,69400,1
3,3,206.474,59.36,542.0,38873.89,119.3,6.895,7.035,6.920,7.020,8.26,516279,YES,185.36,225.344,Drama,45,472,66800,1
4,4,21.381,59.36,542.0,39.701.585,127.7,6.920,7.070,6.815,7.070,8.26,531448,NO,176.48,225.792,Drama,55,395,72400,1

In [ ]:
iris_filename = '/content/Iris.csv'
iris = pd.read_csv(iris_filename, sep = ',',
                   decimal = ',', header = None,
                   names = ['sepal_length',
                            'sepal_width',
                            'petal_length',
                            'petal_width',
                            'target'])

In [ ]:
iris.head()

     sepal_length   sepal_width   petal_length   petal_width       target
Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.10          3.50           1.40          0.20  Iris-setosa
2            4.90          3.00           1.40          0.20  Iris-setosa
3            4.70          3.20           1.30          0.20  Iris-setosa
4            4.60          3.10           1.50          0.20  Iris-setosa

In [ ]:
iris.tail()

    sepal_length sepal_width petal_length petal_width          target
146         6.70        3.00         5.20        2.30  Iris-virginica
147         6.30        2.50         5.00        1.90  Iris-virginica
148         6.50        3.00         5.20        2.00  Iris-virginica
149         6.20        3.40         5.40        2.30  Iris-virginica
150         5.90        3.00         5.10        1.80  Iris-virginica

In [ ]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'target'], dtype='object')

In [ ]:
iris['target'] #target adalah nama kolom
# iris['nama kolom']

Id            Species
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
150    Iris-virginica
Name: target, Length: 151, dtype: object

In [ ]:
iris.target
# nama variabel data.nama kolom
# tidak bisa untuk nama kolom yg ada spasi

Id            Species
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
150    Iris-virginica
Name: target, Length: 151, dtype: object

In [ ]:
# menjadikan kolom target menjadi index
iris.set_index('target', inplace = True)
print(iris.head())

              sepal_length   sepal_width   petal_length   petal_width
target
Species      SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Iris-setosa           5.10          3.50           1.40          0.20
Iris-setosa           4.90          3.00           1.40          0.20
Iris-setosa           4.70          3.20           1.30          0.20
Iris-setosa           4.60          3.10           1.50          0.20

In [ ]:
# menghapus index yang sdh dibuat
iris.reset_index(drop = True, inplace = True)

In [ ]:
iris

      sepal_length   sepal_width   petal_length   petal_width
0    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
1             5.10          3.50           1.40          0.20
2             4.90          3.00           1.40          0.20
3             4.70          3.20           1.30          0.20
4             4.60          3.10           1.50          0.20
..             ...           ...            ...           ...
146           6.70          3.00           5.20          2.30
147           6.30          2.50           5.00          1.90
148           6.50          3.00           5.20          2.00
149           6.20          3.40           5.40          2.30
150           5.90          3.00           5.10          1.80

[151 rows x 4 columns]

In [ ]:
iris_filename = '/content/Iris.csv'
iris = pd.read_csv(iris_filename)

In [ ]:
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
#Melakukan operasi aritmatika
#Hitung perbandingan antara panjang dan lebar sepal untuk setiap target, dan
iris['sepal_ratio'] = iris['SepalLengthCm']/iris['SepalWidthCm']
print (iris.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

   sepal_ratio
0     1.457143
1     1.633333
2     1.468750
3     1.483871
4     1.388889

In [ ]:
# Mengginakan .apply() untuk operasi kostum Hitung luas petal (panjang petal x lebar petal) untuk setiap target
# dan tambahkan DataFrame sebagai kolom baru
# axis = 0 itu baris. axis = 1 itu kolom
iris['petal_area'] = iris.apply(lambda row: row['PetalLengthCm'] * row['PetalWidthCm'], axis = 1)
print (iris.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

   sepal_ratio  petal_area
0     1.457143        0.28
1     1.633333        0.28
2     1.468750        0.26
3     1.483871        0.30
4     1.388889        0.28

In [ ]:
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sepal_ratio,petal_area
0,1,5.1,3.5,1.4,0.2,Iris-setosa,1.457143,0.28
1,2,4.9,3.0,1.4,0.2,Iris-setosa,1.633333,0.28
2,3,4.7,3.2,1.3,0.2,Iris-setosa,1.468750,0.26
3,4,4.6,3.1,1.5,0.2,Iris-setosa,1.483871,0.30
4,5,5.0,3.6,1.4,0.2,Iris-setosa,1.388889,0.28
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,2.233333,11.96
146,147,6.3,2.5,5.0,1.9,Iris-virginica,2.520000,9.50
147,148,6.5,3.0,5.2,2.0,Iris-virginica,2.166667,10.40
148,149,6.2,3.4,5.4,2.3,Iris-virginica,1.823529,12.42
149,150,5.9,3.0,5.1,1.8,Iris-virginica,1.966667,9.18